### ISSUE TITLE
Typings request for lodash 4

### ISSUE THREAD

**Issue by bertyhell** [typings/registry#162]
The registry defaults to v3 for lodash
Is there a way to install v4?

**Comment by blakeembrey** [comment]
Yes. Install using the GitHub syntax mentioned in the Typings README. I think this is the same issue as https://github.com/typings/typings/issues/260, but it's even harder to fix because there's zero versions on DefinitelyTyped. Feel free to open an issue on DefinitelyTyped, that would solve it too.

**Comment by stevehipwell** [comment]
There is a v4 definition in DefinitelyTyped but the api is only returning v3.10.

**Comment by unional** [comment]
If you `tyings install lodash` without `--ambient`, you are using the registry version, which would be v4
https://github.com/typings/registry/blob/master/npm/lodash.json#L3

**Comment by blakeembrey** [comment]
There's at least a few issues logged on this one alone. Either open an issue on DefinitelyTyped to fix the version or we'd love help collaborate on improving the indexing provided by the API. It's difficult to index DefinitelyTyped properly because there's mediocre structure and very few versions noted. The issue here is that `3.x` is properly versioned, but `4.x` is not so it defaults to `0.0.0`.

I can't think of any good fix other than removing all versions from all of DefinitelyTyped.

**Comment by blakeembrey** [comment]
But as @unional has mentioned, our registry actually contains versions and you can just use that instead.
