### ISSUE TITLE
How to reference typings on an npm module with typings.

### ISSUE THREAD

**Issue by andrew-w-ross** [typings/registry#356]
Hi I currently maintain the [typings-redux](https://github.com/andrew-w-ross/typings-redux). [Redux](https://github.com/reactjs/redux) now officially has typings so I would like to remove my own typings and use theirs. 

I could ask the library authors to add a `typings.json` but this doesn't seem like a good solution. The `package.json` already contains the version number and the reference to their type definition. I can easily see a library author forgetting to publish to the registry.

This also feels like part of a bigger problem that will get bigger with libraries now embedding typings inside of their project [moment](https://github.com/moment/moment) is also doing it.

**Comment by blakeembrey** [comment]
You don't need to reference it, TypeScript will already pick it up. If you must use it with Typings (for whatever reason, perhaps you're still on TypeScript 1.4 or something) you can do `typings install npm:redux`. There is no reason anyone should add a `typings.json`.

**Comment by andrew-w-ross** [comment]
@blakeembrey I think we are missing each other here or you guys have done some voodoo I don't know about.

I'm going to remove my redux typings from the registry from as the redux officially supports, as previously discussed. 

I have another type definition for [redux-thunk](https://github.com/gaearon/redux-thunk), that relies on redux. Are you saying that after I remove my definitions doing `npm install npm:redux` is going to correctly reference the one in the actual npm or the npm folder in the registry?

**Comment by blakeembrey** [comment]
I'm still torn on whether you actually should remove them from the registry. Luckily, removing the reference doesn't break anyone (unless you delete the repo too) but, on the other hand, it's possible older `redux` clients may want type definitions. Either way, it's up to you as the owner of them.

The other type definition should continue working fine. If it's Typings dependency, it's already being inlined and won't conflict with the official Redux typings. However, they may end up diverging since it's being inlined. Things start to get a little trickier now, but you can change the dependency in `typings.json` of `redux-thunk` to be `npm:redux` instead.

**Comment by andrew-w-ross** [comment]
I don't want to be a bother but I want to make sure I got this right. If I make the dependency to redux-thunk typings change to `npm:redux` it'll know that the dependency is in npm module itself right? What about version numbers will `npm:redux@3.2.1` work and `npm:redux@^3.2.1`?

If removing `redux-thunk` from the registry is going to be an issue I won't do so but is it possible to add a deprecation notice to that registry entry?

**Comment by blakeembrey** [comment]
@andrew-w-ross Sadly I removed the deprecated notices recently because people were confused. There's no proper way to do it now, but you are allowed to remove the entry from the registry (that does not delete it from the API, just hides it). Using `npm:redux` is only the lookup mechanism (you can read about it on the Typings README) and it _can_ fail if `redux` is not installed. I don't have a better solution for hybrid right now, I only tried to make it partly possible. The other solution here, of course, is to point to the Redux typings on GitHub (but you might be getting versions before they are released).
