### ISSUE TITLE
Moving from dt/node to env/node

### ISSUE THREAD

**Issue by zelein** [typings/registry#749]
Hey,

I'm posting this here as I didn't know where else to post..

I just moved from the dt/node@4 to the env/node@4 and the latest change to env-node has broken my builds. I'm using the dt version of express with "express-serve-static-core" virtual module.

That module is not playing nicely with the recent change to node-env (as it shouldn't) since it is referencing deprecated http modules. What is the recommended upgrade path to get express working again?

Referencing this pull: #748 and this issue: [env-node #34](https://github.com/types/env-node/issues/34)

**Comment by felixfbecker** [comment]
@zelein the express-server-static-core typings are simply wrong. They use the `ServerRequest` typing for `req`, when it really should be `IncomingMessage`. https://github.com/types/npm-express should behave correctly, I advise you to use these typings instead of the DT express typings.

**Comment by felixfbecker** [comment]
Just ran a build with the updated typings, everything is green 👍 
https://travis-ci.org/types/npm-express/builds/157127590

**Comment by zelein** [comment]
Okay, great. I will work on switching that over. I'm having problems integrating the new typings express with some custom Swagger types. But I will work that out.

**Comment by felixfbecker** [comment]
One way they differ is that they do not add `body` to `req` by default. You have to manually combine types where you used a middleware that modifies `req`, like `req: Request & ParsedAsText`.

**Comment by zelein** [comment]
Is there a way to augment the express types?

**Comment by felixfbecker** [comment]
No, you have to do it explicitly with union types. It allow you to selectively only enable properties on `req` where you actually used the middleware.

**Comment by felixfbecker** [comment]
I'm sure it would be possible with some workaround, but honestly it's a bad pattern. The properties are only available when you actually used the middleware, so you should also type Request explicitly with the added attributes

**Comment by zelein** [comment]
> so you should also type Request explicitly with the added attributes

And by that you mean anywhere I am using express.Request, I have to extend it with a Union like you stated above?

**Comment by felixfbecker** [comment]
yes :)
if you have a middleware that is applied to your own app, you could also make it easier by defining a type alias for this or writing an interface that extends from `express.Request`.

**Comment by zelein** [comment]
Thanks for the help Felix. It really is unfortunate that even for TypeScript 2.0, the [@types/express](https://www.npmjs.com/package/@types/express) is using what is currently in DefinitelyTyped, not the correct one that is in Typings.

**Comment by felixfbecker** [comment]
Yes, they publish from DT, even though types has much higher quality typings. See https://github.com/Microsoft/types-publisher/issues/51 and https://github.com/Microsoft/types-publisher/issues/4

**Comment by blakeembrey** [comment]
@zelein Sorry for that deletion. I run into the bug myself when I started using `npm~express` yesterday and wanted to make sure no one else hits the deprecated pattern. Because, like I did, it's likely people don't check the docs and used the types that made the most sense.

I also started following the intersection pattern over union which is really much nicer and can avoid some issues around when a middleware is unused. I still use module augmentation in one place, which is for a global middleware function.

Should we close this and log an issue on DefinitelyTyped to stop using the deprecated http interfaces?

**Comment by felixfbecker** [comment]
> I also started following the intersection pattern over union which is really much nicer 

Could you elaborate? This is only available in TS 2.0, right?

**Comment by zelein** [comment]
Thanks for the response.

Sure, close the issue out. Something definitely needs to be done to sync
the two declaration files. At best, the DT node types should become the
typings types.. And I've read through the issues Felix outlined.

I noticed recently Webstorm telling me http.ClientResponse has been
deprecated by incoming message but I thought it was coming in 6.X (we are
using LTS) so I mentally scheduled it to be done during that upgrade. I
didn't know (and most people probably don't realize) that it is already out
of 4.x.

**Comment by blakeembrey** [comment]
@felixfbecker Sorry, using `express.Request & bodyParser.parsedAsUrlEncoded`.

@zelein The odd thing is, it's been out forever (even 0.10 used `IncomingMessage` and doesn't have any `ClientResponse` or `ServerRequest` classes). I haven't done the detective work, but I'm guessing the implementation in `node.d.ts` was just wrong and no one wanted to fix it because it breaks everyone - but better sooner than later. See https://nodejs.org/docs/latest-v0.10.x/api/http.html.

**Comment by zelein** [comment]
Wow, yeah. It will probably break a lot of people's TS projects. It should probably be done at some point, especially once the TS 2.0 types gets figured out. Ideally the typings version will get the preference since it is the most accurate.
