### ISSUE TITLE
Should definitions that make it into the registry have tests?

### ISSUE THREAD

**Issue by johnnyreilly** [typings/registry#90]
I realised that the definitions in the registry had no sign of tests that I could see. 

Whilst the tests in Definitely Typed are not your classic unit tests per se and actually just test that compilation of code is possible with the definitions available they are useful to have in place to catch any breaking changes people might introduce. This was necessary since DT is a giant repo which contains all the definitions and this does not apply to Typings. That said, is there a desire/need for some kind of testing around the typings that end up in the registry?

If so, what would make sense / be useful in Typings-land?

**Comment by unional** [comment]
Would adding test harness into https://github.com/unional/generator-typings a good place to start?

**Comment by unional** [comment]
The next step is to run the test inside `typings publish` when it is implemented.

**Comment by johnnyreilly** [comment]
> run the test inside typings publish when it is implemented.

I think I need to read up on this. This sounds promising!

**Comment by blakeembrey** [comment]
There's definitely a plan to add a test command that'll run the current Typings against a TypeScript file and emit errors, but I'd also like that command to emit JavaScript so we can use the output for traditional unit tests. The only fuzzy part is whether this command is run on each individual typing or whether it's also part of the registry. If it is part of the registry, we need to be a little more prescriptive than allowing a shell script. Thoughts?

**Comment by unional** [comment]
Will these test need to be hand-crafted or can be generated automatically?
Or is there a need to hand-craft extra tests besides what can be generated automatically?

IMO auto-generated tests can be run from individual typing project and registry, the other should only run from the typing project.

Tests on registry will be run by the bot that check if there is any update from the typings projects?

**Comment by johnnyreilly** [comment]
> whether this command is run on each individual typing or whether it's also part of the registry.

I'm totally on the fence. I'd love to hear the pro's and con's as you see them.

**Comment by blakeembrey** [comment]
@unional I think they'll be hand-crafted. What do you imagine we can automatically generate?

> Tests on registry will be run by the bot that check if there is any update from the typings projects?

I don't think there'll be a need for a bot on this, it'll be part of the CI. However, it depends on the next point.

> I'm totally on the fence. I'd love to hear the pro's and con's as you see them.

So, from the perspective of running tests on each individual typing (E.g. tests are set up locally like NPM).

**Pros:**

* Bring your own test suite (tape, mocha, etc)
* Ease of running functional tests under node or browser or Electron or ... (whatever else comes up)

**Cons**

* Can't run the tests (easily) as part of CI, since they are all customised

Here's the issue I created to do this: https://github.com/typings/typings/issues/3

For more clarity, here's an example. I can run a browser library test easily if we emit JavaScript from the test command. It becomes something of a pipeline like: `typings test | browserify | tape-run`. However, we won't have any knowledge of how to run that as part of the CI step when merging a PR. On the other hand, if we make the test suite prescriptive (e.g. define the files, etc) we can run it on CI but we'd make it harder to adopt new ways of running the test suite.

In the end, I feel like giving power to the user is the best action (even if 99% of tests end up looking the same as the first one we write). There's also the use-case that these test suites need to work on regular JavaScript packages, not just typings projects - E.g. providing a test suite for typings in Express. It means we lose the ability to check if it's passing or failing on merge, but that's ok (I think) because we don't need to be merging on pass/fail - theoretically the community will help handle that.

**Comment by johnnyreilly** [comment]
> In the end, I feel like giving power to the user is the best action (even if 99% of tests end up looking the same as the first one we write). 

That makes sense to me. If there's decent guidance and examples available for people to refer to I think people will use it. I like the flexibility this approach offers also.

> can't run the tests (easily) as part of CI, since they are all customised

This I think would be a shame. People often open PRs which handle their own use cases but break other people's. Fortunately a CI build surfaces these earlier rather than later and saves whoever's reviewing the PR the pain of finding out later.  Not being able to run tests as part of CI would be a real loss.

**Comment by unional** [comment]
> People often open PRs which handle their own use cases but break other people's

Would typings has this issue? As it is just a matter to getting the right shape of the module.

**Comment by johnnyreilly** [comment]
I would imagine it would still be a problem. If someone amends a type definition that other typings depend upon in a way that and breaks compatibility.

**Comment by unional** [comment]
> What do you imagine we can automatically generate

I was thinking something like t4 and tests can automagically generated. :stuck_out_tongue_winking_eye: 

@johnnyreilly , do you have any idea on how the test can be written? I'm actually still learning how the "test" are utilized in DT.

**Comment by blakeembrey** [comment]
@unional The tests in DT are only checking that the compiler actually runs without error, nothing more. To improve upon this, we should also offer proper unit test capabilities to catch if the runtime definition is actually different.

> I was thinking something like t4 and tests can automagically generated.

Sorry, I didn't understand this. What's t4? I'm not sure how easily things can be automatically generated, but it sounds like a bit of work to achieve?

**Comment by unional** [comment]
t4 is Text Template Transformation Toolkit:
http://www.hanselman.com/blog/T4TextTemplateTransformationToolkitCodeGenerationBestKeptVisualStudioSecret.aspx

Basically is getting the d.ts file and transform it to test. Another way is to use `tsc` directly to work on the tokens.

Yeah, it may not be easy to do. Just an idea. :smile:

**Comment by unional** [comment]
I thought about using jspm to dynamically load the module and run tests in the module. That sounds fun. :smile:

**Comment by blakeembrey** [comment]
Closing as individual repositories can contain tests for now. We'll trust our contributors and try to make it easier for people to contribute to those repos as they go.
